name: Update My EPG
on:
  schedule:
    - cron: '0 17 * * *' # Berjalan otomatis jam 12 malam WIB
  workflow_dispatch:      # Tombol untuk jalankan manual

jobs:
  grab-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Grab VisionPlus
        run: npm run grab -- --site=visionplus.id --lang=id --output=visionplus.xml

      - name: Grab Vidio
        run: npm run grab -- --site=vidio.com --output=vidio.xml

      - name: Grab Indihome
        run: npm run grab -- --site=indihometv.com --output=indihome.xml

      - name: Grab Sky Sports NZ
        run: npm run grab -- --site=sky.co.nz --output=skynz.xml

      - name: Grab UNIFI
        run: npm run grab -- --site=playtv.unifi.com.my --output=unifi.xml

      - name: Grab SKY
        run: npm run grab -- --site=sky.com --output=sky.xml

      - name: Commit and Push to Repository
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add visionplus.xml vidio.xml indihome.xml skynz.xml unifi.xml sky.xml
          git commit -m "Update EPG: $(date)" || exit 0
          git push




